### ISSUE TITLE
EOF error when loading app with Python 3.11

### ISSUE THREAD

**Issue by sethbam9** [annotation/text-fabric#78]
## Code:
```python
A = use('bhsa', hoist=globals(), checkout='latest', version='2021', silent='deep')
```

## Error stack trace:

```python
There was an error loading corpus bhsa
EOFError('Ran out of input')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tf/advanced/app.py", line 549, in findApp
    app = appClass(
          ^^^^^^^^^
  File "/Users/sethhowell/text-fabric-data/github/etcbc/bhsa/app/app.py", line 6, in __init__
    super().__init__(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tf/advanced/app.py", line 154, in __init__
    api = TF.load("", silent=silent)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tf/core/fabric.py", line 403, in load
    self._precompute()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tf/core/fabric.py", line 1022, in _precompute
    if not self.features[fName].load(silent=isSilent()):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tf/core/data.py", line 141, in load
    good = self._readDataBin(_withGc=_withGc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tf/core/data.py", line 640, in _readDataBin
    self.data = pickle.load(f)
```

**Comment by dirkroorda** [comment]
Hi @sethbam9 
This could have been caused by an interrupted earlier call.
When TF loads feature data, it reads plain text .tf files and computes a binary representation of that file and saves it as a .tfx file in a .tf directory nearby.
If during this process Ctrl+C is pressed, a binary file may end up with incomplete data.

I can try to anticipate this and recover from it in a next version of TF.

For the moment you can also remove the .tf directory.

Look for it in `~/text-fabric-data/github/ETCBC/bhsa/tf`

**Comment by dirkroorda** [comment]
I just wrote a fix, so that TF can recover from a faulty binary file by recreating it from the textual file.
It is in version 11.0.7

```
pip install --upgrade 'text-fabric[all]'
```
