### ISSUE TITLE
Issue with api (AttributeError: 'Api' object has no attribute 'L')

### ISSUE THREAD

**Issue by yonatanlou** [annotation/text-fabric#84]
Hi,
Im working with mac (Ventura 13).
After the running the following commands:

```
pip install text-fabric
tf ETCBC/dss
```

I get the following error:
```
This is Text-Fabric 12.3.5
Setting up TF browser for tisch
**Locating corpus resources ...**
The requested app is not available offline
	~/text-fabric-data/github/annotation/app-tisch/code not found
Status: latest release online v2.3.1 versus None locally
downloading app, main data and requested additions ...
File is not a zip file
	could not save corpus data to ~/text-fabric-data/github Backend provider github not supported.
Cannot reach online data on github
Try installing text-fabric one of the following:
pip install text-fabric[github]
pip install text-fabric[all]
The requested app is not available offline
  0.00s Not all of the warp features otype and oslots are present in
None/tisch
  0.00s Only the Feature and Edge APIs will be enabled
  0.00s Warp feature "otext" not found. Working without Text-API

Loading TF corpus data. Please wait ...
Traceback (most recent call last):
  File "/opt/anaconda3/bin/tf", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/tf/browser/start.py", line 245, in main
    webapp = setup(debug, *cargs)
             ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/tf/browser/web.py", line 253, in setup
    webapp = factory(web)
             ^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/tf/browser/web.py", line 129, in factory
    app.register_blueprint(nerFactory(web))
                           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/tf/browser/ner/web.py", line 70, in factory
    web.annotate = Annotate(tfApp, data=data, browse=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/tf/browser/ner/annotate.py", line 126, in __init__
    super().__init__(data=data)
  File "/opt/anaconda3/lib/python3.11/site-packages/tf/browser/ner/sets.py", line 47, in __init__
    super().__init__(data=data)
  File "/opt/anaconda3/lib/python3.11/site-packages/tf/browser/ner/data.py", line 62, in __init__
    super().__init__()
  File "/opt/anaconda3/lib/python3.11/site-packages/tf/browser/ner/corpus.py", line 58, in __init__
    L = api.L
        ^^^^^
AttributeError: 'Api' object has no attribute 'L'
```

Thanks!

**Comment by yonatanlou** [comment]
Solve it with:
```
pip uninstall text-fabric
pip instal 'text-fabric[github]'
```

**Comment by dirkroorda** [comment]
Apologies.

The code that loads a TF dataset has seen a great deal of evolution over time, and, frankly, it is almost a mess now, except that it works, most of the time.

Nevertheless, it should also work without the extra `[github]`, but only if there is a file `complete.zip` in the latest release of ETCBC/dss.

I'll check that.

**Comment by dirkroorda** [comment]
Indeed, I have never put a complete.zip in the DSS. Will do that tomorrow.

**Comment by dirkroorda** [comment]
@yonatanlou I have added the complete.zip to the latest release of this repo.

Next time somebody does `tf ETCBC/dss` to get the data from GitHub, it will work, and there will be no rate-limit issues, and it will also work if text-fabric has been installed without the `[github]` extra option.
